language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- travis/deploy.sh
env:
  global:
  - secure: qs7iuQDq0oQreJS3hNsgVfbgIvSVszZY0smWxuAv8uUcLyea1AjejIZmjqnIHPmlfLHhFEX9ufR+aV7G8r6+swQB4axRCZBojAyzyq8GH0YCZ8lNn1O0vbUywiq6K2SikpotxTXl6ohPyydrXLyIOgSg5vZCslq4FrGdJqbqdGN0aVUajfY+NfyY1m9v1kWgDyABNDZo2lsFJmV9mcyUeGKogXvJmVXiQKOypERFVOdArWM9mgNf9+yx/w8NU4MoHSkmYGf28zJTS7MjcTFHDwnZoubuTMdicksoZUIRczWvG5GaaIKLShbB1UzkOG6YjGPHca7LvinUw/23yaxp2yfel3RMZ3At9t1neDY15+kDvhGUkg4eWp3z9PvTAWYXs+lL82i+9cZfQa41C5AHTkDSARVmtZhwR/+7/QeV/EhyV9+oa61GNfZJaElSd4TUzUV2Myztt7RM/vKGjiEn4EFVODidEusaVs+qQAcEbszjqCM4PfI0UyRxa1Fvkt0CYTuRkX3kr2iZByf2nEMr3oKSm82webOLfS9/LHJ8UvaBL2SlGmwDuBPHksTInnUi+V1HocrjUumQWj21WGXH7Yy3GOFfUJLxLOdMSJZ+ZFFPpwWkO9lBRoWDafAsU5dsCi1yf/RKlveGQQ53VStpCOJTCySOwWJ64TarcVsBzJs=
  - secure: bHtd49VkGyPve87+tt4+Q05VQZCU+/0kSxpqAbHJJ7J2/fBK3bD6KnVXZh5Y8J+6nnu6URgywGxpraNSdbzs1T2OqNq0GXt53vLMLi6yvadbcJf3yRO+AIt8HJxVLsgfEaIPnkjEIFtcXXOz++pWqRsAU+1307ZK/VJO1M44D+3rS63lQB0ThVEZluTo14YTB4Kx93NN8HGa0u/ehYBc0tGu0+pMQ8OsxP32sXCPnG1N9EF3mJZasDQzYwrrhLwFrVkfBOYaDylUehhZuebMNr5cjQpzt3WQxYVlrxqwFDZirVCNqMilIMhllBm07AE8jqF/JcCCkpJEs8R6v9MAwqN6wF3yfCBiPLldwEV2J3CuxSv08CZHTIDpCe6Edo3dYXGcyxEh39sil7W3YJSFrupagoeFB3r+WwcbCE+TmRzgsya6GuYJ37xLjbpi916k6+ZiAefExDhv8p08YZ/VkVfEFTFS+N3Z9dLeEGKVa43APatlH63qqT3BioMJhqobJsTicxo3IVwEwrBvWpV55EF0T1LATmtwj+0j5cJmOFqX4wSNgdHE2aBmNMc3z87T7yY3hyNIqw98a0zJcTtHX14zpoL0ZOt9PVcrt22cOQu33TpYEysfAnotejziAeh1MNCQeSF/JgqGzJawsIarZTb3FB+Xm3uQG+au1SSQT1k=
